version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Install celerystalk
          command: |
              apt-get update
              apt-get install git -y
              bash ./setup/install.sh
      - run:
          name: Run unit tests
          command: |
            python -m unittest tests.testing




