version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout # check out the code in the project directory
      - run: apt-get update && apt-get install git -y && ./setup/install.sh
      - run: ls -altR
      - run: cd celerystalk && python -m unittest tests.testing
