version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout # check out the code in the project directory
      - run:
          command: |-
            apt-get update
            apt-get install git -y
            ./setup/install.sh
          name: Install celerystalk
          command: |-
            pwd
            cd ~/project/celerystalk
            python -m unittest tests.testing
          name: Run unit tests
